server:
  port: 8091

spring:
  application:
    name: AuthorizationServer

# DataSource Configuration
  datasource:
    url: jdbc:postgresql://localhost:5432/auth_server
    username: ldamuleli
    password: Lodav72#

# JPA/Hibernate Configuration
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
