server:
  port: 8091

spring:
  application:
    name: AuthorizationServer

# DataSource Configuration
  datasource:
    url: jdbc:postgresql://13.247.97.16:5432/auth_server

    #url: jdbc:postgresql://localhost:5432/authserverdb

    username: postgres
    password: Lodav72#
    driver-class-name: org.postgresql.Driver

# JPA/Hibernate Configuration
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
